#!/bin/bash
# trend-scanner.sh — Scan trending AI/cyber/tech topics for video ideas
# Usage: ./trend-scanner.sh [output_dir]
# Designed to run daily via cron or manually

set -euo pipefail

OUTPUT_DIR="${1:-$(dirname "$0")/../research}"
DATE=$(date +%Y-%m-%d)
OUTPUT_FILE="$OUTPUT_DIR/trends-${DATE}.md"

mkdir -p "$OUTPUT_DIR"

echo "# Trending Topics — ${DATE}" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "_Auto-generated by trend-scanner.sh_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# --- Hacker News Top Stories ---
echo "## 🔶 Hacker News — Top AI/Tech Stories" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Fetch top 30 story IDs, get titles
TOP_IDS=$(curl -sf "https://hacker-news.firebaseio.com/v0/topstories.json" | python3 -c "
import sys, json
ids = json.load(sys.stdin)[:30]
print(' '.join(str(i) for i in ids))
" 2>/dev/null || echo "")

if [ -n "$TOP_IDS" ]; then
    for id in $TOP_IDS; do
        STORY=$(curl -sf "https://hacker-news.firebaseio.com/v0/item/${id}.json" 2>/dev/null || echo "{}")
        TITLE=$(echo "$STORY" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('title',''))" 2>/dev/null || echo "")
        SCORE=$(echo "$STORY" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('score',0))" 2>/dev/null || echo "0")
        URL=$(echo "$STORY" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('url',''))" 2>/dev/null || echo "")
        
        # Filter for AI/tech/security keywords
        if echo "$TITLE" | grep -qiE "AI|LLM|GPT|neural|model|train|GPU|cyber|hack|secur|docker|linux|self-host|homelab|open.?source|rust|python|server|VRAM|fine.?tun|LoRA|agent|MCP|supply.?chain|vuln"; then
            echo "- **${TITLE}** (⬆${SCORE}) — ${URL}" >> "$OUTPUT_FILE"
        fi
    done
else
    echo "_Failed to fetch HN stories_" >> "$OUTPUT_FILE"
fi
echo "" >> "$OUTPUT_FILE"

# --- Reddit: Key Subreddits ---
echo "## 🔴 Reddit — Hot Posts" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for SUB in LocalLLaMA selfhosted homelab cybersecurity comfyui; do
    echo "### r/${SUB}" >> "$OUTPUT_FILE"
    REDDIT=$(curl -sf -H "User-Agent: TAYoutube-Scanner/1.0" \
        "https://www.reddit.com/r/${SUB}/hot.json?limit=5" 2>/dev/null || echo "{}")
    
    echo "$REDDIT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for post in data.get('data', {}).get('children', [])[:5]:
        d = post.get('data', {})
        title = d.get('title', 'Unknown')
        score = d.get('score', 0)
        url = f\"https://reddit.com{d.get('permalink', '')}\"
        print(f'- **{title}** (⬆{score}) — {url}')
except:
    print('_Failed to fetch_')
" >> "$OUTPUT_FILE" 2>/dev/null || echo "_Failed to fetch r/${SUB}_" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

# --- GitHub Trending ---
echo "## 🐙 GitHub Trending (AI/ML)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# GitHub trending doesn't have an official API, use the search API instead
curl -sf "https://api.github.com/search/repositories?q=created:>$(date -d '7 days ago' +%Y-%m-%d 2>/dev/null || date -v-7d +%Y-%m-%d 2>/dev/null || echo '2026-03-17')+language:python+topic:ai&sort=stars&order=desc&per_page=10" 2>/dev/null | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for repo in data.get('items', [])[:10]:
        name = repo.get('full_name', '')
        desc = repo.get('description', 'No description')[:100]
        stars = repo.get('stargazers_count', 0)
        url = repo.get('html_url', '')
        print(f'- **{name}** ⭐{stars} — {desc} — {url}')
except:
    print('_Failed to fetch GitHub trending_')
" >> "$OUTPUT_FILE" 2>/dev/null || echo "_Failed to fetch GitHub trending_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# --- ArXiv Latest AI Papers ---
echo "## 📄 ArXiv — Latest Notable Papers" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

curl -sf "http://export.arxiv.org/api/query?search_query=cat:cs.AI+OR+cat:cs.CR&sortBy=submittedDate&sortOrder=descending&max_results=10" 2>/dev/null | python3 -c "
import sys, xml.etree.ElementTree as ET
data = sys.stdin.read()
root = ET.fromstring(data)
ns = {'atom': 'http://www.w3.org/2005/Atom'}
for entry in root.findall('atom:entry', ns)[:10]:
    title = entry.find('atom:title', ns).text.strip().replace('\n', ' ')
    link = entry.find('atom:id', ns).text.strip()
    print(f'- **{title}** — {link}')
" >> "$OUTPUT_FILE" 2>/dev/null || echo "_Failed to fetch ArXiv_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# --- Summary ---
LINES=$(wc -l < "$OUTPUT_FILE")
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "_Scanned at $(date '+%Y-%m-%d %H:%M %Z'). ${LINES} lines of research._" >> "$OUTPUT_FILE"

echo "✅ Trend scan complete → ${OUTPUT_FILE}"
echo "   ${LINES} lines of research generated"
